plugins {
    id 'fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'
    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.+"
//    id 'java'
//    id 'com.github.johnrengelman.shadow' version '1.2.2'
}

configurations {
    register("shadow") {
        canBeResolved = false
        extendsFrom(modImplementation)
    }
}

version = project.mod_version
group = project.maven_group

base {
    if (project.hasProperty("mod_extradata") && !project.mod_extradata.isEmpty()) {
        archivesName = project.archives_base_name + "-mc" + project.minecraft_version + "-" + project.mod_extradata;
    } else {
        archivesName = project.archives_base_name + "-mc" + project.minecraft_version
    }
}



dependencies {
    //to change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modApi ('com.terraformersmc:modmenu:9.2.0') {
        transitive = false
    }

    modApi("me.shedaniel.cloth:cloth-config-fabric:13.0.138") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    //un-comment those if you want to load from local maven (don't have both local and jitpack sources on at the same time, dunno what it'd do I never tried it)
    //modApi "ch.njol.minecraft:ui-framework-mc1_19_3:${project.ui_framework_version}"
    //include "ch.njol.minecraft:ui-framework-mc1_19_3:${project.ui_framework_version}"
    //modApi "ch.njol.minecraft:config-framework-mc1_19:${project.config_framework_version}"
    //include "ch.njol.minecraft:config-framework-mc1_19:${project.config_framework_version}"
    //un-comment those if you want to load from jitpack (don't have both local and jitpack sources on at the same time, dunno what it'd do I never tried it)
    modApi(include('com.github.Ascynx:MCConfigFramework:mc1.20.4-SNAPSHOT'))
    modApi(include('com.github.Ascynx:MCUIFramework:mc1.20.4-SNAPSHOT'))
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    withSourcesJar()
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.terraformersmc.com" }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://jitpack.io/" }
}

sourceSets {
    main {
        java {
            srcDir("src/java")
        }
        resources {
            srcDir("src/resources")
        }
    }
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        include "fabric.mod.json"
        expand project.properties
        duplicatesStrategy = 'include'
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude "fabric.mod.json"
        duplicatesStrategy = 'include'
    }
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

jar {
    from("LICENSE") {
        rename { "${it}_${archives_base_name}"}
    }
}
//shadowJar {
//    dependencies {
//        include(dependency('me.shedaniel.cloth:cloth-config-fabric:.*'))
//    }
//}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            // add all the jars that should be included when publishing to maven
            artifact(remapJar) {
                builtBy remapJar
            }
        }
    }

    // select the repositories you want to publish to
    repositories {
        // uncomment to publish to the local maven
        // mavenLocal()
    }
}