name: Build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
      - "img"
      - "README.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
      - "img"
      - "README.md"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_URL: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }}
      REF_NAME: ${{ github.ref_name }}
      GITHUB_ACTOR: ${{ secrets.ACTOR }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: Artifact
          path: build/libs/*.jar